- hosts: localhost
  become: true
  become_user: ryan
  vars_files:
    - ./vars/vars.yml
    - ./vars/secrets.yml
  vars_prompt:
    - name: user_password_ryan
      prompt: Enter password for user ryan
      private: yes
      encrypt: sha512_crypt
      confirm: yes
      salt_size: 7
  tasks:
    - name: create custom fact directory
      become: false
      file:
        path: /etc/ansible/facts.d
        state: directory
    - name: install custom fact files
      become: false
      copy:
        src: './facts/{{item}}.fact'
        dest: '/etc/ansible/facts.d/{{item}}.fact'
        mode: 0755
      with_items:
        - rust
        - pacman
    - name: re-run setup to load custom facts
      setup:
        filter: ansible_local
    - name: install packages as root
      become: false
      pacman:
        state: present
        name:
          - openssh
    - name: create user
      become: false
      user:
        name: ryan
        password: '{{user_password_ryan}}'
        groups: wheel
        generate_ssh_key: true
        ssh_key_bits: 4096
        ssh_key_comment: ryan@ryanchipman.com
        ssh_key_passphrase: TODO
        ssh_key_type: rsa
    - name: sudoers entry
      become: false
      copy:
        content: '%wheel ALL=(ALL) ALL'
        dest: /etc/sudoers.d/wheel
    - name: netctl profiles
      become: false
      template:
        src: './templates/netctl/{{item}}'
        dest: '/etc/netctl/{{item}}'
      with_items:
        - mead
        - mongodb
        - lbeach
        - iota
        - iphone-usb
    - name: install packages
      become: false
      pacman:
        state: present
        name:
          - acpi
          - alsa-utils # for alsamixer and amixer
          - dunst
          - emacs
          - firefox
          - go
          - graphviz # needed by a variety of tools
          - htop
          - intel-ucode
          - isync # for syncing email
          - iw # for manually setting up wifi connections
          - ledger
          - libimobiledevice
          - lxterminal
          - pavucontrol
          - rofi-pass
          - stow
          - tmux
          - unzip
          - usbmuxd
          - vim
          - vlc
          - xcape
          - xorg
          - zathura
          - zathura-pdf-mupdf # actually need to install backends for zathura
    - name: install aur helper
      shell: |
        rm -rf /tmp/aur-helper
        git clone https://aur.archlinux.org/yay-bin.git /tmp/aur-helper
        cd /tmp/aur-helper
        makepkg --install --syncdeps --asdeps --noconfirm --noprogressbar
        rm -rf /tmp/aur-helper
    - name: install aur packages
      shell: 'yay -S --nodiffmenu --noeditmenu --noconfirm {{item}}'
      when: item not in ansible_facts.ansible_local.pacman.packages_installed
      with_items:
        - i3lock-wrapper
        - mu-git
        - stumpwm-git
        - ttf-monaco
        - ttf-ms-fonts
        - zoom
    - name: ensure directories for github repos exist
      file:
        path: '/home/ryan/{{item}}'
        state: directory
      with_items:
        - git/sol/
        - git/personal/
        - .go/src/github.com/10gen/
    - name: download github repos
      git:
        repo: 'git@github.com:{{item.repo}}'
        dest: '/home/ryan/{{item.path}}'
        update: false
      with_items:
        - { repo: 'rychipman/dotfiles', path: '.dotfiles' }
        - { repo: 'rychipman/password-store', path: '.password-store' }
        - { repo: 'rychipman/ledger', path: 'ledger' }
        - { repo: 'rychipman/org', path: 'org' }
        - { repo: 'rychipman/plaint', path: 'git/personal/plaint' }
        - { repo: 'rychipman/kludger', path: 'git/personal/kludger' }
        - { repo: 'solsensor/sol', path: 'git/sol/sol' }
        - { repo: '10gen/sqlproxy', path: '.go/src/github.com/10gen/sqlproxy' }
    - name: remove typical stow conflicts
      file:
        state: absent
        path: '{{item}}'
      with_items:
        - /home/ryan/.bashrc
        - /home/ryan/.bash_profile
    - name: enable stow configs
      shell: STOW_DIR=/home/ryan/.dotfiles stow bash bin dunst emacs git ledger lxterminal mbsync mongodb pass rust ssh stow stumpwm tmux vim
      args:
        chdir: /home/ryan
    - name: ensure mbsync secrets directory exists
      file:
        path: /home/ryan/.local/share/secrets/mbsync
        state: directory
    - name: deploy mbsync mongodb secret
      copy:
        content: '{{mbsync_mongodb_password}}'
        dest: /home/ryan/.local/share/secrets/mbsync/mongodb
    - name: deploy mbsync personal secret
      copy:
        content: '{{mbsync_personal_password}}'
        dest: /home/ryan/.local/share/secrets/mbsync/personal
    - name: create mailboxes
      file:
        path: '/home/ryan/mail/{{item}}'
        state: directory
      with_items:
        - mongodb
        - personal
    - name: install rustup
      shell: 'curl --proto =https --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y'
      when: not ansible_facts.ansible_local.rust.rustup_installed
