- hosts: localhost
  become: true
  vars_prompt:
    - name: user_password_ryan
      prompt: Enter password for user ryan
      private: yes
      encrypt: sha512_crypt
      confirm: yes
      salt_size: 7
    - name: ssh_key_password_ryan
      prompt: Enter password for ryan's ssh key
      private: yes
      confirm: yes
  tasks:
    - name: install packages
      pacman:
        state: present
        name:
          - acpi
          - dunst
          - firefox
          - go
          - graphviz
          - htop
          - intel-ucode
          - isync
          - iw
          - ledger
          - lxterminal
          - openssh
          - pavucontrol
          - rofi-pass
          - stow
          - tmux
          - unzip
          - vim
          - vlc
          - xcape
          - zathura
          #- mu
          #- i3lock-wrapper
          #- ttf-monaco
          #- zoom
          #- yay
    - name: create users
      user:
        name: ryan
        password: '{{user_password_ryan}}'
        generate_ssh_key: true
        ssh_key_bits: 4096
        ssh_key_comment: ryan@ryanchipman.com
        ssh_key_passphrase: '{{ssh_key_password_ryan}}'
        ssh_key_type: rsa
    - pause:
        prompt: enter a random value
      register: random_value_pause
    - debug:
        msg: 'random variable value: {{random_value_pause.user_input}}'
    - name: create random file
      file:
        state: touch
        path: '/home/ryan/{{random_value_pause.user_input}}'
    - name: download dotfiles
      git:
        repo: https://github.com/rychipman/dotfiles
        dest: /home/ryan/.dotfiles
    - name: remove typical stow conflicts
      file:
        state: absent
        path: '{{item}}'
      with_items:
        - /home/ryan/.bashrc
        - /home/ryan/.bash_profile
    - name: basic stow setup
      shell: STOW_DIR=/home/ryan/.dotfiles stow bash bin git ssh stow
      args:
        chdir: /home/ryan
    - name: stumpwm setup
      shell: STOW_DIR=/home/ryan/.dotfiles stow stumpwm
      args:
        chdir: /home/ryan
