- hosts: localhost
  become: true
  become_user: ryan
  vars_files:
    - ./vars/vars.yml
    - ./vars/secrets.yml
  vars_prompt:
    - name: user_password_ryan
      prompt: Enter password for user ryan
      private: yes
      encrypt: sha512_crypt
      confirm: yes
      salt_size: 7
  tasks:
    - name: install packages as root
      become: false
      pacman:
        state: present
        name:
          - openssh
    - name: create user
      become: false
      user:
        name: ryan
        password: '{{user_password_ryan}}'
        groups: wheel
        generate_ssh_key: true
        ssh_key_bits: 4096
        ssh_key_comment: ryan@ryanchipman.com
        ssh_key_passphrase: TODO
        ssh_key_type: rsa
    - name: sudoers entry
      become: false
      copy:
        content: '%wheel ALL=(ALL) ALL'
        dest: /etc/sudoers.d/wheel
    - name: netctl profiles
      become: false
      template:
        src: './templates/netctl/{{item}}'
        dest: '/etc/netctl/{{item}}'
      with_items:
        - mead
        - mongodb
    - name: install packages
      become: false
      pacman:
        state: present
        name:
          - acpi
          - alsa-utils # for alsamixer and amixer
          - dunst
          - emacs
          - firefox
          - go
          - graphviz # needed by a variety of tools
          - htop
          - intel-ucode
          - isync # for syncing email
          - iw # for manually setting up wifi connections
          - ledger
          - lxterminal
          - pavucontrol
          - rofi-pass
          - stow
          - tmux
          - unzip
          - vim
          - vlc
          - xcape
          - xorg
          - zathura
          - zathura-pdf-mupdf # actually need to install backends for zathura
    - name: install aur helper
      shell: |
        rm -rf /tmp/aur-helper
        git clone https://aur.archlinux.org/yay-bin.git /tmp/aur-helper
        cd /tmp/aur-helper
        makepkg --install --syncdeps --asdeps --noconfirm --noprogressbar
        rm -rf /tmp/aur-helper
    - name: install aur packages
      shell: 'yay -S --nodiffmenu --noeditmenu --noconfirm {{item}}'
      with_items:
        - i3lock-wrapper
        - mu-git
        - stumpwm-git
        - ttf-monaco
        - zoom
    - name: download dotfiles
      git:
        repo: https://github.com/rychipman/dotfiles
        dest: /home/ryan/.dotfiles
    - name: remove typical stow conflicts
      file:
        state: absent
        path: '{{item}}'
      with_items:
        - /home/ryan/.bashrc
        - /home/ryan/.bash_profile
    - name: enable stow configs
      shell: STOW_DIR=/home/ryan/.dotfiles stow bash bin dunst emacs git ledger lxterminal mbsync mongodb pass rust ssh stow stumpwm tmux vim
      args:
        chdir: /home/ryan
