- hosts: localhost
  become: true
  tasks:
    - name: install packages
      pacman:
        name: {{item}}
        state: present
      with_items:
        - htop
        - tmux
        - acpi
        - dunst
        - zathura
        - firefox
        - go
        - graphviz
        - i3lock-wrapper
        - intel-ucode
        - isync
        - iw
        - ledger
        - lxterminal
        - mu
        - pavucontrol
        - rofi-pass
        - stow
        - ttf-monaco
        - unzip
        - vim
        - vlc
        - xcape
        - zoom
        - yay
