- hosts: localhost
  become: true
  tasks:
    - name: install packages
      pacman:
        state: present
        name:
          - htop
          - tmux
          - acpi
          - dunst
          - zathura
          - firefox
          - go
          - graphviz
          - intel-ucode
          - isync
          - iw
          - ledger
          - lxterminal
          - pavucontrol
          - rofi-pass
          - stow
          - unzip
          - vim
          - vlc
          - xcape
          #- mu
          #- i3lock-wrapper
          #- ttf-monaco
          #- zoom
          #- yay
